set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'

set -g @plugin 'maxpetretta/tmux-monokai-pro'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'sainnhe/tmux-fzf'

# Start window count from 1 (more accessible) and renumber windows after deletion
set -g base-index 1
set -g renumber-windows on
# Top status bar
set -g status-position top
# Restore last (auto-)saved session
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
