gui:
  theme:
    activeBorderColor:
      - "#f9cc6c"
      - bold
    inactiveBorderColor:
      - "#adda78"
    searchingActiveBorderColor:
      - "#85dacc"
      - bold
    optionsTextColor:
      - "#c3b7b8"
    selectedLineBgColor:
      - "#4b4242"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#c3b7b8"
    cherryPickedCommitBgColor:
      - "#85dacc"
    markedBaseCommitFgColor:
      - "#85dacc"
    markedBaseCommitBgColor:
      - "#fd6883"
    unstagedChangesColor:
      - "#fd6883"
    defaultFgColor:
      - "#fff1f3"
os:
  # edit: "zeditor -- {{filename}}"
  # editAtLine: "zeditor -- {{filename}}:{{line}}"
  # editAtLineAndWait: "zeditor --wait -- {{filename}}:{{line}}"
  # openDirInEditor: "zeditor -- {{dir}}"
  edit: "vscodium --reuse-window -- {{filename}}"
  editAtLine: "vscodium --reuse-window --goto -- {{filename}}:{{line}}"
  editAtLineAndWait: "vscodium --reuse-window --goto --wait -- {{filename}}:{{line}}"
  openDirInEditor: "vscodium -- {{dir}}"
  editInTerminal: false
