gui:
  theme:
    activeBorderColor:
      - "#ffd866"
      - bold
    inactiveBorderColor:
      - "#a9dc76"
    searchingActiveBorderColor:
      - "#78dce8"
      - bold
    optionsTextColor:
      - "#c1c0c0"
    selectedLineBgColor:
      - "#c1c0c0"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#c1c0c0"
    cherryPickedCommitBgColor:
      - "#78dce8"
    markedBaseCommitFgColor:
      - "#78dce8"
    markedBaseCommitBgColor:
      - "#ff6188"
    unstagedChangesColor:
      - "#ff6188"
    defaultFgColor:
      - "#fcfcfa"
os:
  # edit: "zeditor -- {{filename}}"
  # editAtLine: "zeditor -- {{filename}}:{{line}}"
  # editAtLineAndWait: "zeditor --wait -- {{filename}}:{{line}}"
  # openDirInEditor: "zeditor -- {{dir}}"
  edit: "vscodium --reuse-window -- {{filename}}"
  editAtLine: "vscodium --reuse-window --goto -- {{filename}}:{{line}}"
  editAtLineAndWait: "vscodium --reuse-window --goto --wait -- {{filename}}:{{line}}"
  openDirInEditor: "vscodium -- {{dir}}"
  editInTerminal: false
