[colors]
draw_bold_text_with_bright_colors = true
[colors.bright]
black = "#665c54"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#fbf1c7"
yellow = "#fabd2f"

[colors.cursor]
cursor = "#d5c4a1"
text = "#282828"

[colors.normal]
black = "#282828"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#d5c4a1"
yellow = "#fabd2f"

[colors.primary]
background = "#282828"
bright_foreground = "#fbf1c7"
foreground = "#d5c4a1"

[colors.selection]
background = "#504945"
text = "#d5c4a1"

[cursor.style]
blinking = "Off"
shape = "Block"

[cursor.vi_mode_style]
blinking = "Off"
shape = "Beam"

[font]
size = 13
[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[mouse]
hide_when_typing = false

[terminal]
osc52 = "OnlyCopy"

[window]
opacity = 1.0

[window.padding]
x = 15
y = 15
